import { useState, useRef, useEffect, useCallback } from "react";

const CW_BLUE = "#003087";
const CW_RED  = "#E4002B";

function CWLogo() {
  return (
    <div style={{ display:"flex", alignItems:"center", gap:0, flexShrink:0 }}>
      <svg width="52" height="46" viewBox="0 0 80 52" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M22 5 C6 5 1 16 3 28 C5 35 9 40 14 43" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M54 5 C70 5 75 16 73 28 C71 35 67 40 62 43" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M22 5 C22 17 30 27 38 34" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M54 5 C54 17 46 27 38 34" stroke="white" strokeWidth="5" strokeLinecap="round" fill="none"/>
        <path d="M29 24 L38 38 L47 24" stroke="white" strokeWidth="4.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
      </svg>
      <div style={{ width:1, height:32, background:"rgba(255,255,255,0.3)", margin:"0 12px" }} />
      <span style={{ color:"white", fontFamily:"Arial,sans-serif", fontWeight:"700", fontSize:"17px", letterSpacing:"2px", whiteSpace:"nowrap" }}>
        CONNECTWISE<sup style={{ fontSize:"8px", marginLeft:1 }}>®</sup>
      </span>
    </div>
  );
}

const PRODUCTS = [
  "Cybersecurity / MDR","Cybersecurity / SIEM","Cybersecurity / EDR",
  "Cybersecurity / AI SOC","Cybersecurity / Vulnerability Management",
  "RMM","PSA / ConnectWise Manage","Other",
];

const SECTIONS = [
  "Executive Summary","PRD Summary Table","Objectives & Outcomes","Scope",
  "Partner Segmentation","Feature Comparison","Feature Gaps & Pain Points",
  "Success KPIs","Assumptions & Dependencies","Milestones & Phased Delivery",
  "Personas & Usage Scenarios","Detailed Requirements Table",
  "Non-Functional Requirements","Migration Requirements","Release Readiness",
  "Risks & Mitigation","Quantitative Insights","Out of Scope","Reference Links",
];

const SYSTEM_PROMPT = `You are a senior Product Manager at ConnectWise. ConnectWise serves MSPs, MSSPs, and TSPs (called "partners") who use ConnectWise products for their end clients. Core products: RMM, PSA, MDR, SIEM, EDR, AI SOC, Vulnerability Management.

Generate a complete PRD in Markdown with ALL 19 sections below. Be detailed and specific.

# PRD: [Title]
**Version:** 1.0 | **Date:** ${new Date().toLocaleDateString()} | **Status:** Draft

## 1. Executive Summary
## 2. PRD Summary Table
| Field | Details |
|---|---|
| Product Area | |
| Feature Name | |
| Priority | |
| Target Release | |
| PM Owner | |
| Partner Segments | MSP / MSSP / TSP |

## 3. Objectives & Outcomes
### Business Objectives
### Desired Outcomes
### Why Now?

## 4. Scope
### In Scope
### Out of Scope

## 5. Partner Segmentation
| Partner Type | Key Need | Impact |
|---|---|---|
| MSP | | |
| MSSP | | |
| TSP | | |

## 6. Feature Comparison Across Products
| Feature | Current State | Proposed State | Competitor |
|---|---|---|---|

## 7. Feature Gaps and Pain Points
### Feature Gaps
### Migration Challenges
### Display Issues
### Data Integrity Concerns

## 8. Success KPIs
| KPI | Baseline | Target | How Measured |
|---|---|---|---|

## 9. Assumptions & Dependencies
### Assumptions
### Dependencies

## 10. Milestones & Phased Delivery
| Phase | Milestone | Target Date | Owner |
|---|---|---|---|

## 11. Personas and Usage Scenarios
### Primary Persona
### Other Personas
### Key Scenarios
### Step-by-Step Examples

## 12. Detailed Requirements Table
| ID | Requirement | Priority | User Story | Acceptance Criteria |
|---|---|---|---|---|
| REQ-001 | | Must Have | As a partner, I want... | |
(minimum 8 requirements)

## 13. Non-Functional Requirements
| Category | Requirement | Target |
|---|---|---|

## 14. Migration Requirements

## 15. Release Readiness Requirements
| Team | Requirements | Owner |
|---|---|---|

## 16. Risks & Mitigation
| Risk | Likelihood | Impact | Mitigation |
|---|---|---|---|

## 17. Quantitative Insights

## 18. Out of Scope

## 19. Reference Links
| Resource | Link |
|---|---|
| ConnectWise Docs | https://docs.connectwise.com |

---
*Generated by ConnectWise PRD Generator*`;

const ENHANCE_SYSTEM = `You are a ConnectWise product manager. Take a brief requirement and expand it into a richer 150-250 word brief that will produce a higher-quality PRD. Add context about MSP/MSSP/TSP partner impact, business value, pain points, and scale. Return only the enhanced brief with no extra labels or preamble.`;

// ── Markdown Renderer ────────────────────────────────────────────────────────
function MDRenderer({ content }) {
  if (!content) return null;
  const renderInline = (text) =>
    text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((p, i) => {
      if (/^\*\*(.+)\*\*$/.test(p)) return <strong key={i}>{p.replace(/\*\*/g,"")}</strong>;
      if (/^`(.+)`$/.test(p)) return <code key={i} style={{ background:"#f0f4ff", padding:"1px 4px", borderRadius:3, fontSize:12 }}>{p.replace(/`/g,"")}</code>;
      return p;
    });
  const lines = content.split("\n");
  const els = [];
  let i = 0;
  while (i < lines.length) {
    const ln = lines[i];
    if (/^# /.test(ln))   { els.push(<h1 key={i} style={{ fontSize:22, fontWeight:800, color:CW_BLUE, margin:"20px 0 8px", borderBottom:`3px solid ${CW_RED}`, paddingBottom:6 }}>{ln.slice(2)}</h1>); i++; continue; }
    if (/^## /.test(ln))  { els.push(<h2 key={i} style={{ fontSize:16, fontWeight:700, color:CW_BLUE, margin:"18px 0 6px", borderLeft:`4px solid ${CW_RED}`, paddingLeft:10 }}>{ln.slice(3)}</h2>); i++; continue; }
    if (/^### /.test(ln)) { els.push(<h3 key={i} style={{ fontSize:14, fontWeight:700, color:"#222", margin:"12px 0 4px" }}>{ln.slice(4)}</h3>); i++; continue; }
    if (/^---/.test(ln))  { els.push(<hr key={i} style={{ border:"none", borderTop:"1px solid #e0e6f0", margin:"10px 0" }} />); i++; continue; }
    if (/^\|/.test(ln) && i+1 < lines.length && /^\|[-| :]+\|/.test(lines[i+1])) {
      const tLines = [];
      while (i < lines.length && /^\|/.test(lines[i])) { tLines.push(lines[i]); i++; }
      const headers = tLines[0].split("|").slice(1,-1).map(c=>c.trim());
      const rows = tLines.slice(2).map(r=>r.split("|").slice(1,-1).map(c=>c.trim())).filter(r=>r.some(c=>c&&!/^[-:]+$/.test(c)));
      els.push(
        <div key={`t${i}`} style={{ overflowX:"auto", margin:"8px 0 14px" }}>
          <table style={{ borderCollapse:"collapse", width:"100%", fontSize:12.5 }}>
            <thead><tr style={{ background:CW_BLUE }}>{headers.map((h,hi)=><th key={hi} style={{ padding:"8px 12px", color:"white", textAlign:"left", whiteSpace:"nowrap" }}>{h}</th>)}</tr></thead>
            <tbody>{rows.map((row,ri)=><tr key={ri} style={{ background:ri%2===0?"#f7f9fd":"white" }}>{row.map((cell,ci)=><td key={ci} style={{ padding:"6px 12px", borderBottom:"1px solid #e8ecf4", verticalAlign:"top" }}>{renderInline(cell)}</td>)}</tr>)}</tbody>
          </table>
        </div>
      );
      continue;
    }
    if (/^[-*] /.test(ln))  { els.push(<li key={i} style={{ marginLeft:20, marginBottom:3, fontSize:13, lineHeight:1.6 }}>{renderInline(ln.replace(/^[-*] /,""))}</li>); i++; continue; }
    if (/^\d+\. /.test(ln)) { els.push(<li key={i} style={{ marginLeft:22, marginBottom:3, fontSize:13, listStyleType:"decimal", lineHeight:1.6 }}>{renderInline(ln.replace(/^\d+\. /,""))}</li>); i++; continue; }
    if (!ln.trim())         { els.push(<div key={i} style={{ height:5 }} />); i++; continue; }
    els.push(<p key={i} style={{ fontSize:13, margin:"2px 0", lineHeight:1.7, color:"#333" }}>{renderInline(ln)}</p>);
    i++;
  }
  return <div style={{ fontFamily:"'Segoe UI',system-ui,sans-serif" }}>{els}</div>;
}

function Chip({ label, color=CW_BLUE }) {
  return <span style={{ background:`${color}18`, color, border:`1px solid ${color}30`, borderRadius:20, padding:"3px 10px", fontSize:11, fontWeight:600, whiteSpace:"nowrap" }}>{label}</span>;
}

// ── Voice Button ─────────────────────────────────────────────────────────────
function VoiceButton({ onTranscript, disabled }) {
  const [listening, setListening] = useState(false);
  const [supported, setSupported] = useState(true);
  const recogRef = useRef(null);

  useEffect(() => {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { setSupported(false); return; }
    const r = new SR();
    r.continuous = true; r.interimResults = true; r.lang = "en-US";
    let final = "";
    r.onresult = (e) => {
      let interim = "";
      for (let i = e.resultIndex; i < e.results.length; i++) {
        if (e.results[i].isFinal) final += e.results[i][0].transcript + " ";
        else interim += e.results[i][0].transcript;
      }
      onTranscript(final + interim, false);
    };
    r.onend = () => { setListening(false); onTranscript(final.trim(), true); final = ""; };
    r.onerror = () => setListening(false);
    recogRef.current = r;
  }, [onTranscript]);

  if (!supported) return null;

  const toggle = () => {
    if (listening) { recogRef.current?.stop(); setListening(false); }
    else { recogRef.current?.start(); setListening(true); }
  };

  return (
    <button onClick={toggle} disabled={disabled} title={listening?"Stop recording":"Speak your requirement"}
      style={{
        width:40, height:40, borderRadius:"50%", border:"none",
        cursor:disabled?"not-allowed":"pointer",
        background: listening ? CW_RED : `${CW_BLUE}15`,
        color: listening ? "white" : CW_BLUE,
        fontSize:17, display:"flex", alignItems:"center", justifyContent:"center",
        flexShrink:0, transition:"all .2s",
        boxShadow: listening ? `0 0 0 4px ${CW_RED}35, 0 0 0 8px ${CW_RED}15` : "none",
        animation: listening ? "micPulse 1.2s ease-in-out infinite" : "none",
      }}>
      {listening ? "⏹" : "🎤"}
    </button>
  );
}

// ── DOCX generator (no external library — uses HTML blob) ────────────────────
function downloadAsWord(mdText, filename) {
  const htmlContent = mdText
    .replace(/^# (.+)$/gm, '<h1 style="color:#003087;border-bottom:3px solid #E4002B;padding-bottom:6px;">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#003087;border-left:4px solid #E4002B;padding-left:10px;">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #e0e6f0;"/>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li>$2</li>');

  // Convert markdown tables to HTML tables
  const withTables = (() => {
    const lines = htmlContent.split("\n");
    const result = [];
    let i = 0;
    while (i < lines.length) {
      if (/^\|/.test(lines[i]) && i+1 < lines.length && /^\|[-| :]+\|/.test(lines[i+1])) {
        const headers = lines[i].split("|").slice(1,-1).map(c=>c.trim());
        i += 2; // skip header and separator
        const rows = [];
        while (i < lines.length && /^\|/.test(lines[i])) {
          rows.push(lines[i].split("|").slice(1,-1).map(c=>c.trim()));
          i++;
        }
        let table = `<table border="1" style="border-collapse:collapse;width:100%;font-size:12px;margin:10px 0;">`;
        table += `<tr style="background:#003087;color:white;">${headers.map(h=>`<th style="padding:8px;text-align:left;">${h}</th>`).join("")}</tr>`;
        rows.forEach((row,ri) => {
          table += `<tr style="background:${ri%2===0?"#f7f9fd":"white"};">${row.map(c=>`<td style="padding:6px 8px;border:1px solid #e0e6f0;">${c}</td>`).join("")}</tr>`;
        });
        table += `</table>`;
        result.push(table);
      } else {
        result.push(lines[i]);
        i++;
      }
    }
    return result.join("\n");
  })();

  const fullHtml = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8"/>
      <title>ConnectWise PRD</title>
      <!--[if gte mso 9]>
      <xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml>
      <![endif]-->
      <style>
        body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #333; line-height: 1.6; margin: 2cm; }
        h1 { font-size: 18pt; color: #003087; border-bottom: 2pt solid #E4002B; padding-bottom: 4pt; }
        h2 { font-size: 14pt; color: #003087; border-left: 4pt solid #E4002B; padding-left: 8pt; margin-top: 16pt; }
        h3 { font-size: 12pt; margin-top: 12pt; }
        table { border-collapse: collapse; width: 100%; margin: 8pt 0; font-size: 10pt; }
        th { background: #003087; color: white; padding: 6pt 8pt; text-align: left; }
        td { padding: 5pt 8pt; border: 1pt solid #e0e6f0; }
        tr:nth-child(even) td { background: #f7f9fd; }
        li { margin-bottom: 3pt; }
        p { margin: 4pt 0; }
      </style>
    </head>
    <body>${withTables}</body></html>`;

  const blob = new Blob([fullHtml], { type:"application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename + ".doc";
  a.click();
  URL.revokeObjectURL(url);
}

// ── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [tab,         setTab]         = useState("input");
  const [input,       setInput]       = useState("");
  const [voiceInterim,setVoiceInterim]= useState("");
  const [pmName,      setPmName]      = useState("");
  const [product,     setProduct]     = useState(PRODUCTS[0]);
  const [priority,    setPriority]    = useState("High");
  const [prdText,     setPrdText]     = useState("");
  const [loading,     setLoading]     = useState(false);
  const [enhancing,   setEnhancing]   = useState(false);
  const [error,       setError]       = useState("");
  const [progress,    setProgress]    = useState(0);
  const [history,     setHistory]     = useState([]);
  const [viewingHist, setViewingHist] = useState(null);
  const [copied,      setCopied]      = useState(false);
  const outputRef = useRef(null);

  const completedSections = SECTIONS.filter((_,idx) => {
    const n = idx+1;
    return prdText.includes(`## ${n}.`) || prdText.includes(`## ${n} `);
  }).length;

  // Voice handler
  const handleVoice = useCallback((text, isFinal) => {
    if (isFinal) { setInput(t => (t + " " + text).trim()); setVoiceInterim(""); }
    else setVoiceInterim(text);
  }, []);

  // ── API call helper ────────────────────────────────────────────────────────
  const callAPI = async (system, userMsg) => {
    const res = await fetch("/api/generate-prd", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "claude-haiku-4-5",
        max_tokens: 2500,
        system,
        messages: [{ role:"user", content: userMsg }]
      })
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data?.error || `Server error ${res.status}`);
    return (data.content || []).map(b => b.text || "").join("");
  };

  // ── Generate PRD — TWO parallel calls to get all 19 sections ───────────────
  const generatePRD = async () => {
    if (!input.trim()) { setError("Please describe your requirement."); return; }
    setError(""); setLoading(true); setPrdText(""); setTab("output"); setProgress(10);
    const iv = setInterval(() => setProgress(p => p < 85 ? p + 3 : p), 800);

    const userMsg = `Product: ${product}\nPriority: ${priority}\nPM: ${pmName || "ConnectWise PM"}\n\nRequirement:\n${input}`;

    const SYSTEM_PART1 = SYSTEM_PROMPT + `\n\nCRITICAL INSTRUCTION: Generate ONLY sections 1 to 7. Stop after ## 7. Feature Gaps and Pain Points. Do NOT write any other sections.`;

    const SYSTEM_PART2 = `You are a senior ConnectWise Product Manager writing a PRD for ${product}.
CRITICAL INSTRUCTION: Generate ONLY these 6 sections. No intro, no preamble, start directly with ## 8.

## 8. Success KPIs
| KPI | Baseline | Target | Measurement Method |
|---|---|---|---|

## 9. Assumptions & Dependencies
### Assumptions
### Dependencies
| Dependency | Type | Team | Risk if Delayed |
|---|---|---|---|

## 10. Milestones & Phased Delivery
| Phase | Milestone | Description | Target Date | Owner |
|---|---|---|---|---|

## 11. Personas and Usage Scenarios
### Primary Persona
### Other Personas
### Key Scenarios
### Step-by-Step Example

## 12. Detailed Requirements Table
| ID | Requirement | Priority | User Story | Acceptance Criteria |
|---|---|---|---|---|
(write minimum 8 rows)

## 13. Non-Functional Requirements
| Category | Requirement | Target |
|---|---|---|`;

    const SYSTEM_PART3 = `You are a senior ConnectWise Product Manager writing a PRD for ${product}.
CRITICAL INSTRUCTION: Generate ONLY these 6 sections. No intro, no preamble, start directly with ## 14.

## 14. Migration Requirements
Describe data migration, partner migration, and rollback strategy.

## 15. Release Readiness Requirements
| Team | Requirements | Owner | Due Date |
|---|---|---|---|

## 16. Risks & Mitigation
| Risk | Likelihood | Impact | Mitigation Strategy | Owner |
|---|---|---|---|---|
(write minimum 5 risks)

## 17. Quantitative Insights
Include market size, partner count affected, ARR impact, support ticket volumes.

## 18. Out of Scope
List all items explicitly excluded with rationale.

## 19. Reference Links
| Resource | Link |
|---|---|
| ConnectWise Product Docs | https://docs.connectwise.com |
| Internal Confluence | [Add internal link] |
| Competitor Analysis | [To be added] |
| Customer Research | [To be added] |

---
*Generated by ConnectWise PRD Generator*`;

    try {
      // Run all 3 calls in parallel
      const [part1, part2, part3] = await Promise.all([
        callAPI(SYSTEM_PART1, userMsg),
        callAPI(SYSTEM_PART2, userMsg),
        callAPI(SYSTEM_PART3, userMsg),
      ]);

      if (!part1.trim()) throw new Error("Empty response from Part 1 — please try again.");
      if (!part2.trim()) throw new Error("Empty response from Part 2 — please try again.");
      if (!part3.trim()) throw new Error("Empty response from Part 3 — please try again.");

      const text = part1.trim() + "\n\n" + part2.trim() + "\n\n" + part3.trim();

      clearInterval(iv); setProgress(100);
      setPrdText(text);
      const title = text.match(/^# PRD: (.+)/m)?.[1] || `PRD — ${product}`;
      setHistory(h => [{ id:Date.now(), title, product, priority, pmName, date:new Date().toLocaleDateString(), prd:text }, ...h.slice(0,19)]);
    } catch(e) {
      clearInterval(iv);
      setError("⚠ " + e.message);
      setTab("input");
    } finally {
      setLoading(false);
      setTimeout(() => setProgress(0), 1000);
    }
  };

  // ── Enhance Prompt ─────────────────────────────────────────────────────────
  const enhancePrompt = async () => {
    if (!input.trim()) { setError("Write a brief requirement first, then enhance it."); return; }
    setEnhancing(true); setError("");
    try {
      const enhanced = await callAPI(ENHANCE_SYSTEM, `Product: ${product}\n\n${input}`);
      if (enhanced) setInput(enhanced);
    } catch(e) { setError("⚠ Enhancement failed: " + e.message); }
    finally { setEnhancing(false); }
  };

  // ── Copy Markdown ──────────────────────────────────────────────────────────
  const copyMd = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  // ── Save as PDF (browser print) ────────────────────────────────────────────
  const saveAsPDF = (text) => {
    const win = window.open("", "_blank");
    win.document.write(`<html><head><title>ConnectWise PRD</title>
    <style>
      body{font-family:Arial,sans-serif;font-size:12px;padding:30px;color:#333;line-height:1.6}
      h1{color:#003087;font-size:20px;border-bottom:3px solid #E4002B;padding-bottom:5px}
      h2{color:#003087;font-size:15px;border-left:4px solid #E4002B;padding-left:8px;margin-top:18px}
      h3{font-size:13px;margin-top:12px;font-weight:700}
      table{border-collapse:collapse;width:100%;margin:8px 0;font-size:11px}
      th{background:#003087;color:white;padding:7px 10px;text-align:left}
      td{padding:5px 10px;border-bottom:1px solid #e0e6f0}
      tr:nth-child(even) td{background:#f7f9fd}
      li{margin-bottom:2px}
      hr{border:none;border-top:1px solid #e0e6f0;margin:8px 0}
      @media print{body{padding:15px}}
    </style></head><body>
    <script>
      const md=${JSON.stringify(text)};
      function mdToHtml(t){
        const lines=t.split("\\n");const out=[];let i=0;
        while(i<lines.length){
          const l=lines[i];
          if(/^\\| /.test(l)&&i+1<lines.length&&/^\\|[-| :]+\\|/.test(lines[i+1])){
            const hcells=l.split("|").slice(1,-1).map(c=>c.trim());
            i+=2;const rows=[];
            while(i<lines.length&&/^\\|/.test(lines[i])){rows.push(lines[i].split("|").slice(1,-1).map(c=>c.trim()));i++;}
            let tbl='<table><thead><tr>'+hcells.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>';
            rows.forEach((r,ri)=>{tbl+='<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>';});
            out.push(tbl+'</tbody></table>');continue;
          }
          if(/^# /.test(l)){out.push('<h1>'+l.slice(2)+'</h1>');}
          else if(/^## /.test(l)){out.push('<h2>'+l.slice(3)+'</h2>');}
          else if(/^### /.test(l)){out.push('<h3>'+l.slice(4)+'</h3>');}
          else if(/^---$/.test(l)){out.push('<hr/>');}
          else if(/^[-*] /.test(l)){out.push('<li>'+l.replace(/^[-*] /,'').replace(/\\*\\*([^*]+)\\*\\*/g,'<strong>$1</strong>')+'</li>');}
          else if(l.trim()===''){out.push('<br/>');}
          else{out.push('<p>'+l.replace(/\\*\\*([^*]+)\\*\\*/g,'<strong>$1</strong>')+'</p>');}
          i++;
        }
        return out.join('');
      }
      document.body.innerHTML='<div>'+mdToHtml(md)+'</div>';
      setTimeout(()=>window.print(),600);
    </script></body></html>`);
    win.document.close();
  };

  // ── Shared button styles ───────────────────────────────────────────────────
  const solidBtn = (bg, label, onClick, disabled=false) => (
    <button onClick={onClick} disabled={disabled} style={{ padding:"8px 16px", background:disabled?"#bbb":bg, color:"white", border:"none", borderRadius:8, fontSize:13, fontWeight:600, cursor:disabled?"not-allowed":"pointer", whiteSpace:"nowrap", display:"flex", alignItems:"center", gap:5 }}>
      {label}
    </button>
  );
  const outlineBtn = (label, onClick) => (
    <button onClick={onClick} style={{ padding:"8px 16px", background:"white", color:CW_BLUE, border:`1.5px solid ${CW_BLUE}`, borderRadius:8, fontSize:13, fontWeight:600, cursor:"pointer", whiteSpace:"nowrap" }}>
      {label}
    </button>
  );

  // ── PRD Action Toolbar (reused in Output + History view) ──────────────────
  const PRDToolbar = ({ text, showBack=false, onBack=null }) => (
    <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:14, flexWrap:"wrap", gap:10 }}>
      <div style={{ display:"flex", gap:8, alignItems:"center", flexWrap:"wrap" }}>
        {showBack && (
          <button onClick={onBack} style={{ padding:"7px 16px", background:"white", border:"1.5px solid #ccc", color:"#333", borderRadius:8, fontSize:13, cursor:"pointer", fontWeight:600 }}>
            ← Back
          </button>
        )}
        {!showBack && <><Chip label={`✅ ${completedSections}/19 sections`} color="#2e7d32" /><Chip label={product} color={CW_BLUE} /><Chip label={priority} color={priority==="High"?CW_RED:priority==="Medium"?"#e67e00":"#555"} /></>}
      </div>
      <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
        {outlineBtn(copied?"✅ Copied!":"📋 Copy Markdown", ()=>copyMd(text))}
        {solidBtn(CW_BLUE, "📄 Save as Word", ()=>downloadAsWord(text, "ConnectWise_PRD"))}
        {solidBtn("#555", "🖨 Save as PDF", ()=>saveAsPDF(text))}
        {showBack && solidBtn(CW_RED, "Open in PRD View →", ()=>{ setPrdText(text); setTab("output"); setViewingHist(null); })}
        {!showBack && solidBtn(CW_RED, "+ New PRD", ()=>{ setPrdText(""); setTab("input"); })}
      </div>
    </div>
  );

  return (
    <div style={{ minHeight:"100vh", background:"#f0f4fb", fontFamily:"'Segoe UI',system-ui,sans-serif" }}>

      {/* ── Header ── */}
      <header style={{ background:CW_BLUE, height:58, display:"flex", alignItems:"center", padding:"0 28px", boxShadow:"0 2px 12px rgba(0,0,80,.3)", position:"sticky", top:0, zIndex:100 }}>
        <CWLogo />
        <span style={{ marginLeft:16, color:"rgba(255,255,255,.6)", fontSize:13 }}>PRD Generator · Product Management</span>
        {history.length > 0 && (
          <button onClick={()=>setTab("history")} style={{ marginLeft:"auto", background:"rgba(255,255,255,.15)", border:"1px solid rgba(255,255,255,.25)", color:"white", padding:"6px 14px", borderRadius:8, cursor:"pointer", fontSize:12, fontWeight:600 }}>
            📚 History ({history.length})
          </button>
        )}
      </header>

      <div style={{ maxWidth:1100, margin:"0 auto", padding:"24px 20px" }}>

        {/* ── Tabs ── */}
        <div style={{ display:"flex", gap:3, marginBottom:22, background:"white", borderRadius:10, padding:4, width:"fit-content", boxShadow:"0 1px 4px rgba(0,0,0,.08)" }}>
          {[["input","📝 Input"],["output",`📄 PRD${prdText?` · ${completedSections}/19`:""}`],["history",`📚 History${history.length?` (${history.length})`:""}`]].map(([id,label])=>(
            <button key={id} onClick={()=>setTab(id)} style={{ padding:"8px 22px", border:"none", cursor:"pointer", borderRadius:8, fontWeight:600, fontSize:13, background:tab===id?CW_BLUE:"transparent", color:tab===id?"white":"#666" }}>{label}</button>
          ))}
        </div>

        {/* ══ INPUT TAB ══ */}
        {tab === "input" && (
          <div style={{ display:"grid", gridTemplateColumns:"1fr 280px", gap:20 }}>
            <div style={{ background:"white", borderRadius:14, padding:28, boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
              <h2 style={{ margin:"0 0 20px", color:CW_BLUE, fontSize:19, fontWeight:800 }}>New PRD</h2>

              <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:14, marginBottom:16 }}>
                <div>
                  <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>Product Area *</div>
                  <select value={product} onChange={e=>setProduct(e.target.value)} style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, background:"white", outline:"none" }}>
                    {PRODUCTS.map(p=><option key={p}>{p}</option>)}
                  </select>
                </div>
                <div>
                  <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>Priority</div>
                  <select value={priority} onChange={e=>setPriority(e.target.value)} style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, background:"white", outline:"none" }}>
                    {["High","Medium","Low"].map(p=><option key={p}>{p}</option>)}
                  </select>
                </div>
              </div>

              <div style={{ marginBottom:16 }}>
                <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6, marginBottom:5 }}>PM Name (optional)</div>
                <input value={pmName} onChange={e=>setPmName(e.target.value)} placeholder="e.g. Jane Smith" style={{ width:"100%", padding:"9px 11px", border:"1.5px solid #dde3f0", borderRadius:8, fontSize:13, outline:"none", boxSizing:"border-box" }} />
              </div>

              <div style={{ marginBottom:16 }}>
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:5 }}>
                  <div style={{ fontSize:11, fontWeight:700, color:"#555", textTransform:"uppercase", letterSpacing:.6 }}>Requirement Description *</div>
                  <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                    <span style={{ fontSize:11, color:"#aaa" }}>{input.trim().split(/\s+/).filter(Boolean).length} words</span>
                    <VoiceButton onTranscript={handleVoice} disabled={loading||enhancing} />
                  </div>
                </div>
                <div style={{ position:"relative" }}>
                  <textarea
                    value={input + (voiceInterim ? " " + voiceInterim : "")}
                    onChange={e=>{ setInput(e.target.value); setVoiceInterim(""); setError(""); }}
                    placeholder="Example: We need AI-powered alert triage in our MDR product. SOC analysts manually review every alert causing fatigue. We want auto-classification by severity, remediation suggestions, and false positive suppression for MSP partners managing 50–500 endpoints per client..."
                    rows={9}
                    style={{ width:"100%", padding:"11px 13px", border:`1.5px solid ${error?CW_RED:"#dde3f0"}`, borderRadius:8, fontSize:13, resize:"vertical", lineHeight:1.7, outline:"none", fontFamily:"inherit", boxSizing:"border-box", background:voiceInterim?"#fffdf0":"white" }}
                  />
                  {voiceInterim && (
                    <div style={{ position:"absolute", bottom:10, right:12, fontSize:11, color:CW_RED, display:"flex", alignItems:"center", gap:4 }}>
                      <span style={{ animation:"blink 1s infinite" }}>●</span> Listening...
                    </div>
                  )}
                </div>
                {error && <div style={{ color:CW_RED, fontSize:12.5, marginTop:5 }}>{error}</div>}
              </div>

              {/* Action buttons */}
              <div style={{ display:"flex", gap:10 }}>
                <button onClick={enhancePrompt} disabled={enhancing||loading} style={{ flex:1, padding:"11px", background:"white", border:`1.5px solid ${CW_BLUE}`, color:CW_BLUE, borderRadius:8, fontSize:13, fontWeight:600, cursor:enhancing?"wait":"pointer", opacity:enhancing?0.6:1 }}>
                  {enhancing ? "✨ Enhancing..." : "✨ Enhance Prompt"}
                </button>
                <button onClick={generatePRD} disabled={loading||enhancing} style={{ flex:2, padding:"11px", background:loading?"#999":`linear-gradient(135deg,${CW_RED},#c00020)`, color:"white", border:"none", borderRadius:8, fontSize:14, fontWeight:700, cursor:loading?"not-allowed":"pointer", boxShadow:loading?"none":`0 3px 12px ${CW_RED}50` }}>
                  {loading ? "⚙️ Generating PRD..." : "🚀 Generate PRD"}
                </button>
              </div>

              {loading && (
                <div style={{ marginTop:14 }}>
                  <div style={{ display:"flex", justifyContent:"space-between", fontSize:12, color:"#666", marginBottom:5 }}>
                    <span>Building all 19 sections...</span><span>{progress}%</span>
                  </div>
                  <div style={{ height:7, background:"#eee", borderRadius:4, overflow:"hidden" }}>
                    <div style={{ height:"100%", width:`${progress}%`, background:`linear-gradient(90deg,${CW_BLUE},${CW_RED})`, borderRadius:4, transition:"width .5s" }} />
                  </div>
                </div>
              )}

              <div style={{ marginTop:14, padding:"9px 13px", background:`${CW_BLUE}08`, borderRadius:8, fontSize:12, color:"#666", display:"flex", alignItems:"center", gap:8 }}>
                🎤 <span>Tap the mic to speak your requirement. Works best in Chrome or Edge.</span>
              </div>
            </div>

            {/* Sidebar */}
            <div style={{ display:"flex", flexDirection:"column", gap:14 }}>
              <div style={{ background:"white", borderRadius:12, padding:18, boxShadow:"0 1px 6px rgba(0,0,0,.08)" }}>
                <div style={{ fontSize:12, fontWeight:700, color:CW_BLUE, marginBottom:12, textTransform:"uppercase", letterSpacing:.6 }}>19 Sections Generated</div>
                {SECTIONS.map((s,i)=>(
                  <div key={i} style={{ display:"flex", alignItems:"center", gap:8, padding:"4px 0", borderBottom:i<18?"1px solid #f2f4f9":"none" }}>
                    <div style={{ width:19, height:19, background:`${CW_BLUE}10`, border:`1px solid ${CW_BLUE}25`, borderRadius:4, display:"flex", alignItems:"center", justifyContent:"center", fontSize:9, color:CW_BLUE, fontWeight:800, flexShrink:0 }}>{i+1}</div>
                    <span style={{ fontSize:11.5, color:"#555" }}>{s}</span>
                  </div>
                ))}
              </div>
              <div style={{ background:`linear-gradient(135deg,${CW_BLUE}0d,${CW_RED}08)`, border:`1px solid ${CW_BLUE}18`, borderRadius:12, padding:16 }}>
                <div style={{ fontSize:12, fontWeight:700, color:CW_BLUE, marginBottom:8, textTransform:"uppercase", letterSpacing:.6 }}>💡 Tips</div>
                {["State partner type: MSP, MSSP, or TSP","Describe the pain & current workaround","Include scale: endpoints, partners","Mention related ConnectWise products","Use 🎤 voice to speak naturally","Hit ✨ Enhance for richer output"].map((tip,i)=>(
                  <div key={i} style={{ fontSize:12, color:"#444", padding:"3px 0", borderBottom:i<5?"1px solid rgba(0,0,80,.06)":"none", display:"flex", gap:6 }}>
                    <span style={{ color:CW_RED }}>›</span>{tip}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* ══ OUTPUT TAB ══ */}
        {tab === "output" && (
          <div>
            {prdText ? (
              <>
                <PRDToolbar text={prdText} />
                <div ref={outputRef} style={{ background:"white", borderRadius:14, padding:36, boxShadow:"0 1px 8px rgba(0,0,0,.08)", maxHeight:"76vh", overflowY:"auto" }}>
                  <MDRenderer content={prdText} />
                </div>
              </>
            ) : (
              <div style={{ background:"white", borderRadius:14, padding:60, textAlign:"center", boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
                <div style={{ fontSize:44, marginBottom:12 }}>📄</div>
                <div style={{ color:"#bbb", fontSize:15, marginBottom:16 }}>No PRD generated yet.</div>
                <button onClick={()=>setTab("input")} style={{ padding:"9px 22px", background:CW_BLUE, color:"white", border:"none", borderRadius:8, cursor:"pointer", fontWeight:700, fontSize:13 }}>← Go to Input</button>
              </div>
            )}
          </div>
        )}

        {/* ══ HISTORY TAB ══ */}
        {tab === "history" && (
          <div>
            {viewingHist ? (
              <div>
                <PRDToolbar text={viewingHist.prd} showBack={true} onBack={()=>setViewingHist(null)} />
                <div style={{ background:"white", borderRadius:14, padding:36, boxShadow:"0 1px 8px rgba(0,0,0,.08)", maxHeight:"76vh", overflowY:"auto" }}>
                  <MDRenderer content={viewingHist.prd} />
                </div>
              </div>
            ) : history.length === 0 ? (
              <div style={{ background:"white", borderRadius:14, padding:60, textAlign:"center", boxShadow:"0 1px 8px rgba(0,0,0,.08)" }}>
                <div style={{ fontSize:44, marginBottom:12 }}>📚</div>
                <div style={{ color:"#bbb", fontSize:15 }}>No PRDs yet. Generate your first one!</div>
              </div>
            ) : (
              <div>
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16 }}>
                  <span style={{ fontSize:14, fontWeight:600, color:"#555" }}>{history.length} saved PRD{history.length>1?"s":""}</span>
                  <button onClick={()=>{ if(window.confirm("Clear all history?")) setHistory([]); }} style={{ padding:"6px 14px", background:"white", border:"1.5px solid #f44", color:"#f44", borderRadius:8, fontSize:12, cursor:"pointer", fontWeight:600 }}>🗑 Clear All</button>
                </div>
                <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))", gap:14 }}>
                  {history.map(h=>(
                    <div key={h.id} onClick={()=>setViewingHist(h)}
                      style={{ background:"white", borderRadius:12, padding:20, boxShadow:"0 1px 6px rgba(0,0,0,.08)", cursor:"pointer", border:"1.5px solid transparent", transition:"all .18s" }}
                      onMouseEnter={e=>e.currentTarget.style.borderColor=CW_BLUE}
                      onMouseLeave={e=>e.currentTarget.style.borderColor="transparent"}>
                      <div style={{ fontSize:13.5, fontWeight:700, color:CW_BLUE, marginBottom:8 }}>{h.title}</div>
                      <div style={{ display:"flex", gap:6, flexWrap:"wrap", marginBottom:8 }}>
                        <Chip label={h.product} color={CW_BLUE} />
                        <Chip label={h.priority} color={h.priority==="High"?CW_RED:h.priority==="Medium"?"#e67e00":"#555"} />
                      </div>
                      <div style={{ display:"flex", justifyContent:"space-between" }}>
                        <span style={{ fontSize:11.5, color:"#bbb" }}>{h.date}</span>
                        {h.pmName && <span style={{ fontSize:11.5, color:"#999" }}>by {h.pmName}</span>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <style>{`
        @keyframes blink { 0%,100%{opacity:1} 50%{opacity:.2} }
        @keyframes micPulse { 0%,100%{box-shadow:0 0 0 4px ${CW_RED}40,0 0 0 8px ${CW_RED}18} 50%{box-shadow:0 0 0 6px ${CW_RED}55,0 0 0 12px ${CW_RED}25} }
        button:hover:not(:disabled) { opacity:0.88; }
        ::-webkit-scrollbar{width:6px} ::-webkit-scrollbar-thumb{background:#c8d0e0;border-radius:4px}
        select:focus,input:focus,textarea:focus{border-color:${CW_BLUE}!important;outline:none}
      `}</style>
    </div>
  );
}
